const scienceQA = [
  {
    text: "What type of energy do we get from the rays of the sun?",
    answer: " Radiant energy",
    choices: [" Radiant energy", "Potential energy"]
  },

  {
    text: "What type of energy can be generated by splitting atoms?",
    answer: " Nuclear energy",
    choices: ["Electrical energy", " Nuclear energy"]
  },

  {
    text: "What is the standard unit of measurement for energy in physics?",
    answer: "Joule",
    choices: ["Watt", "Joule"]
  },

  {
    text: "What type of energy source is generated by hot springs and geysers?",
    answer: "Geothermal power",
    choices: ["Geothermal power", "Hydropower"]
  }
];

const geoQA = [
  {
    text: "What country is also known as Persia?",
    answer: "Iran",
    choices: ["Iran", "Irak"]
  },

  {
    text: "What major river flows through the Grand Canyon?",
    answer: "Colorado River",
    choices: ["Colorado River", "Mississipi River"]
  },

  {
    text: "What city was once called New Amsterdam?",
    answer: "New York",
    choices: ["New York", "Chicago"]
  },

  {
    text: "What is the longest river in the world?",
    answer: "Nil",
    choices: ["Amazone", "Nil"]
  }
];

const artQA = [
  {
    text: "Who painted the ceiling of the Sistine Chapel?",
    answer: "Michelangelo",
    choices: ["Leonardo da Vinci", "Michelangelo"]
  },

  {
    text: "What nationality was Picasso?",
    answer: "Spanish",
    choices: ["Spanish", "Italian"]
  },

  {
    text: "Which Dutch painter cut off part of his ear after a quarrel?",
    answer: "Vincent van Gogh",
    choices: ["Vincent van Gogh", "Lucas van Leyden"]
  },

  {
    text: "In which country can you see the sphinx?",
    answer: "Egypt",
    choices: ["Egypt", "Syria"]
  }
];

const historyQA = [
  {
    text: "Hammurabi is best known for:",
    answer: "Developing a code of law.",
    choices: ["Developing a code of law.", "Conquering Persia"]
  },

  {
    text: "When did world war 1 started?",
    answer: "1914",
    choices: ["1914", "1918"]
  },

  {
    text: "when did world war 2 ended?",
    answer: "1945",
    choices: ["1945", "1932"]
  },

  {
    text: "when did germany become a country?",
    answer: "1990",
    choices: ["1990", "1980"]
  }
];

class Question {
  constructor(category, onQuestionAnswered) {
    this.onQuestionAnswered = onQuestionAnswered;
    this.category = category;
    this.chosenQuestion;
    this.questionDiv;
  }

  getQuestion() {
    if (this.category === "Sci") {
      let index = Math.floor(Math.random() * scienceQA.length);
      this.chosenQuestion = scienceQA[index];
    } else if (this.category === "Hist") {
      let index = Math.floor(Math.random() * historyQA.length);
      this.chosenQuestion = historyQA[index];
    } else if (this.category === "Geo") {
      let index = Math.floor(Math.random() * geoQA.length);
      this.chosenQuestion = geoQA[index];
    } else {
      let index = Math.floor(Math.random() * artQA.length);
      this.chosenQuestion = artQA[index];
    }
  }

  draw() {
    this.questionDiv = createDiv().class("question container");
    const questionText = createDiv(this.chosenQuestion.text).class(
      "questionText"
    );
    this.questionDiv.child(questionText);
    this.chosenQuestion.choices.forEach(choice => {
      const defaultClasses = "btn btn-lg";
      const button = createButton(choice).class(
        `${defaultClasses} btn-warning`
      );
      button.mouseClicked(() => {
        button.class(
          choice === this.chosenQuestion.answer
            ? `${defaultClasses} btn-success`
            : `${defaultClasses} btn-danger`
        );
        setTimeout(() => {
          this.onQuestionAnswered(choice === this.chosenQuestion.answer);
        }, 1000);
      });
      this.questionDiv.child(button);
      this.questionDiv.parent("canvas-container");
    });
  }

  remove() {
    this.questionDiv.remove();
  }
}
